image: registry.gitlab.com/pages/hugo:latest

#variables:
# GIT_SUBMODULE_STRATEGY: recursive

#test:
#  script:
#  - hugo

pages:
 script:
  - build.sh
  artifacts:
    paths:
    - public
  only:
  - master
