image: registry.gitlab.com/pages/hugo:latest

pages:
 script:
  - apk add git
  - git clone https://github.com/gohugoio/hugoBasicExample
  - cd hugoBasicExample
  - git submodule add -f https://gitlab.com/ksksarthik/monopriv themes/monopriv
  - hugo -b https://kskarthik.gitlab.io/monopriv/
 artifacts:
    paths:
    - public
 only:
    - master
