# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "bootstrap-blogdown"
license = "MIT"
licenselink = "https://gitlab.com/kskarthik/monopriv/blob/master/LICENSE"
description = "A Bootstrap Blogdown site based on Sai Karthhik's monopriv"
homepage = "https://gitlab.com/kskarthik/monopriv"
tags = ["minimal", "simple", "clean", "blog", "light","bootstrap", "responsive", "fast", "privacy", "monospace", "monopriv"]
features = ["blogdown", "blog", "Clean and minimal", "Responsive", "Social media links", "Syntax highlighting"]
min_version = "0.41"

[author]
  name = "Sai Karthik (with modifications Jed Stephens)"
  homepage = "https://github.com/JedStephens/bootstrap-blogdown"
